import Head from "next/head";
import { useState } from "react";
import Bar from "../components/Bar";
import styles from "../styles/Home.module.css";
import DataTable from "../components/Data";
import styled from "styled-components";
import Overview from "../components/layouts/Overview";
import ButtonType from "../components/NavButtons";
import { IoNotifications } from "react-icons/io5";

export default function Home() {
  const [buttonId, setButtonId] = useState(1);
  const getButtonId = (e) => {
    setButtonId(parseInt(e.target.id) + 1);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Bar>
        <Main>
          <div className="topbar">
            <div>
              <ButtonType
                buttons={["Overview", "Guess list", "Temporary traffic"]}
                getId={getButtonId}
              />
            </div>
            <div className="notification">
              <p>
                <IoNotifications />
              </p>
              <p className="image"></p>
            </div>
          </div>
          <DataTable />
        </Main>
      </Bar>
    </div>
  );
}

const Main = styled.main`
  width: calc(100% - 251px);
  margin-left: 250px;
  transition: all 300ms ease;
  padding: 0 40px 40px 40px;

  @media (max-width: 768px) {
    width: 100%;
    margin-left: 0;
  }
`;
