import Head from "next/head";
import Bar from "../components/Bar";
import styles from "../styles/Home.module.css";
import DataTable from "../components/Data";
import styled from "styled-components";
import TopBar from "../components/TopBar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Bar>
        <Main>
          <TopBar />
          <DataTable />
        </Main>
      </Bar>
    </div>
  );
}

const Main = styled.main`
  width: calc(100% - 251px);
  margin-left: 250px;
  transition: all 300ms ease;
  padding: 0 40px 40px 40px;

  @media (max-width: 768px) {
    width: 100%;
    margin-left: 0;
  }
`;
